// -----------------------
//     labels.js
//     ver 2.5.0
// -----------------------

const labels = {
  "ja": {

    // メニュー
    "menu-file": "ファイル",
    "menu-add-file": "ファイル追加",
    "menu-export-playlist": "プレイリストエクスポート",
    "menu-import-playlist": "プレイリストインポート",
    "menu-device-settings": "デバイス設定",
    "menu-recording-settings": "録画設定",
    "menu-language": "言語",
    "menu-exit": "終了",
    "menu-edit": "編集",
    "menu-toggle-start-mode": "スタートモード切替（Pause/Play/Fadein）",
    "menu-end-mode-off": "エンドモード：OFF",
    "menu-end-mode-pause": "エンドモード：PAUSE",
    "menu-end-mode-ftb": "エンドモード：FTB",
    "menu-end-mode-repeat": "エンドモード：REPEAT",
    "menu-end-mode-next": "エンドモード：NEXT",
    "menu-reset-edit-area": "エディットエリアリセット",
    "menu-set-in-point": "IN点設定",
    "menu-set-out-point": "OUT点設定",
    "menu-copy-item-state": "アイテム状態コピー",
    "menu-paste-item-state": "アイテム状態貼付",
    "menu-playlist": "プレイリスト",
    "menu-playlist1": "プレイリスト1",
    "menu-playlist2": "プレイリスト2",
    "menu-playlist3": "プレイリスト3",
    "menu-playlist4": "プレイリスト4",
    "menu-playlist5": "プレイリスト5",
    "menu-save-mode": "セーブモード",
    "menu-delete-mode": "削除モード",
    "menu-clear-playlist": "クリア",
    "menu-select-item-up": "アイテム選択（上）",
    "menu-select-item-down": "アイテム選択（下）",
    "menu-on-air": "オンエア",
    "menu-off-air": "オフエア",
    "menu-ftb": "FTB",
    "menu-play-pause": "再生／停止",
    "menu-audio-fade-in": "メイン音声フェードイン",
    "menu-audio-fade-out": "メイン音声フェードアウト",
    "menu-capture-fullscreen": "スクリーンショット",
    "menu-recording-toggle": "録画",
    "menu-dsk-toggle": "DSK のオン／オフ",
    "menu-mode": "モード",
    "menu-list-mode-repeat": "リストモード：REPEAT",
    "menu-list-mode-list": "リストモード：LIST",
    "menu-direct-mode": "ダイレクトモード",
    "menu-soundpad-mode": "サウンドパッドモード",
    "menu-fillkey-mode": "フィルキーモード",
    "menu-window": "ウィンドウ",
    "menu-debug-mode": "デバッグモード",
    "menu-fullscreen": "フルスクリーン",
    "menu-fullscreen-toggle-minimize-maximize": "フルスクリーン画面を最小化/最大化",
    "menu-move-fullscreen": "フルスクリーン移動",
    "menu-tools": "ツール",
    "menu-tools-atem-connection": "ATEM連携",
    "menu-help": "ヘルプ",
    "menu-about": "バージョン情報",
    "menu-check-update": "アップデートの確認",
    "menu-readme": "Readme",
    "menu-reset-edit-area": "エディットエリアリセット",
    "menu-tools-generate-smpte-bars": "SMPTEカラーバー",
    "menu-tools-generate-checker": "カラーチェッカーボード",
    "menu-tools-generate-1khz-tone": "1kHzテストトーン",

    // エリアタイトル
    "edit-title": "編集",
    "playlist-title": "プレイリスト",
    "on-air-title": "オンエアモニタリング",

    // エディット画面
    "in-point": "イン点",
    "out-point": "アウト点",
    "start-mode-title": "スタートモード",
    "start-pause-button": "一時停止",
    "start-play-button": "再生",
    "start-fadein-button": "F/I",
    "end-mode-title": "エンドモード",
    "end-off-button": "オフ",
    "end-pause-button": "ポーズ",
    "end-repeat-button": "繰返し",
    "end-next-button": "次",
    "end-ftb-button": "FTB",
    "ftbRate": "フェードアウト時間（秒）",
    "audio-output-level": "音量設定",
    "audio-output": "音声出力",
    "pfl-button": "PFL",
    "on-air-volume-slider": "音量",
    "uvc-device": "UVCデバイス",
    "other-source-title": "その他ソース",
    "addUVCToPlaylistButton": "リストに追加",
    "still-capture-title": "スチルキャプチャ/PNG/JPG/PPTX動画変換の時間設定",
    "still-button": "キャプチャ",
    "dsk-title": "ダウンストリームキー",
    "dsk-button": "DSK",
    "fadeInDuration": "変換時間（秒）",
    "pptxDissolve": "ディゾルブ",

    // プレイリスト画面
    "list-mode-title": "モード",
    "list-repeat-button": "全リピート",
    "list-list-button": "リストを一巡",
    "directonair-mode-button": "ダイレクト",
    "soundpad-mode-button": "パッド",
    "fillkey-mode-button": "フィルキー",
    "playlist-name-display": "プレイリストストア",
    "playlise-save-button": "保存",
    "playlise1-button": "1",
    "playlise2-button": "2",
    "playlise3-button": "3",
    "playlise4-button": "4",
    "playlise5-button": "5",
    "playlisedel-button": "削除",
    "playliseclear-button": "クリア",
    "file-button": "ファイル追加",
    "cue-button": "オンエア",

    // オンエア画面
    "on-air-item-fo-button": "F/O",
    "on-air-item-fi-button": "F/I",
    "on-air-fo-button": "F/O",
    "on-air-fi-button": "F/I",
    "playback-speed-control": "再生速度",
    "playback-speed-slider": "速度調整",
    "playback-speed-input": "速度",
    "fullscreen-shot": "フルスクリーンキャプチャ / 録画",
    "capture-button": "キャプチャ",
    "rec-button": "録画",
    "off-air-button": "オフエア",
    "ftb-off-button": "FTB",
    "on-air-pause-button": "一時停止",
    "on-air-play-button": "再生",

    // プレイリスト名モーダル
    "playlist-name-title": "プレイリスト名を入力してください",
    "playlist-name-save": "保存",
    "playlist-name-cancel": "キャンセル",

    // コンテキストメニュー（プレイリストアイテム）
    "context-rename-item": "名前の変更",
    "context-start-mode": "スタートモード",
    "context-end-mode": "エンドモード",
    "context-bg-color": "背景色",
    "context-bg-color-default": "標準",
    "context-bg-color-red": "赤",
    "context-bg-color-yellow": "黄",
    "context-bg-color-blue": "青",
    "context-bg-color-green": "緑",
    "context-start-mode-play": "再生",
    "context-start-mode-pause": "一時停止",
    "context-start-mode-fadein": "フェードイン",
    "context-end-mode-next": "次",
    "context-end-mode-off": "オフ",
    "context-end-mode-pause": "一時停止",
    "context-end-mode-repeat": "繰返し",
    "context-end-mode-ftb": "FTB",
    "context-copy-item-state": "アイテムの状態をコピー",
    "context-paste-item-state": "アイテムの状態をペースト",

    // デバイス設定
    "device-settings-title": "デバイス設定",
    "device-loading-message": "デバイスを読み込み中...",
    "audio-section-title": "オーディオ",
    "edit-audio-monitor-label": "PFL オーディオモニターデバイス",
    "onair-audio-output-label": "オンエアオーディオ出力デバイス",
    "uvc-audio-mapping-title": "UVC オーディオマッピング",
    "restore-on-startup-label": "次回起動時にこの設定を復元",

    // 録画設定
    "recording-settings-title": "録画設定",
    "recording-section-title": "録画設定",
    "recording-quality-label": "録画品質",
    "recording-quality-high": "高画質 (10Mbps)",
    "recording-quality-standard": "標準画質 (8Mbps)",
    "recording-quality-performance": "性能優先 (6Mbps)",
    "recording-filename-prefix-label": "ファイル名プレフィックス",
    "recording-save-directory-label": "保存先フォルダー",
    "recording-browse-button": "参照...",
    "recording-ok-button": "OK",

    // ATEM設定
    "atem-settings-title": "ATEM 接続設定",
    "atem-control-enable": "VTR-PON から ATEM を制御",
    "atem-auto-switch-enable": "ATEM から VTR-PON を制御",
    "atem-ip-address-label": "IP アドレス",
    "atem-input-number-label": "ATEMにVTR-PONを入力している番号",
    "atem-switch-delay-label": "切り替えディレイ (ms)",
    "atem-restore-on-startup-label": "次回起動時にこの設定を復元",
    "atem-save-button": "保存",
    "atem-cancel-button": "キャンセル"
  },
  "en": {

    "menu-file": "File",
    "menu-add-file": "Add File",
    "menu-export-playlist": "Export Playlist",
    "menu-import-playlist": "Import Playlist",
    "menu-device-settings": "Device Settings",
    "menu-recording-settings": "Recording Settings",
    "menu-language": "Language",
    "menu-exit": "Exit",
    "menu-edit": "Edit",
    "menu-toggle-start-mode": "Toggle Start Mode (Pause/Play/Fadein)",
    "menu-end-mode-off": "End Mode: OFF",
    "menu-end-mode-pause": "End Mode: PAUSE",
    "menu-end-mode-ftb": "End Mode: FTB",
    "menu-end-mode-repeat": "End Mode: REPEAT",
    "menu-end-mode-next": "End Mode: NEXT",
    "menu-reset-edit-area": "Reset Edit Area",
    "menu-set-in-point": "Set IN Point",
    "menu-set-out-point": "Set OUT Point",
    "menu-copy-item-state": "Copy Item State",
    "menu-paste-item-state": "Paste Item State",
    "menu-playlist": "Playlist",
    "menu-playlist1": "Playlist 1",
    "menu-playlist2": "Playlist 2",
    "menu-playlist3": "Playlist 3",
    "menu-playlist4": "Playlist 4",
    "menu-playlist5": "Playlist 5",
    "menu-save-mode": "Save Mode",
    "menu-delete-mode": "Delete Mode",
    "menu-clear-playlist": "Clear",
    "menu-select-item-up": "Select Item (Up)",
    "menu-select-item-down": "Select Item (Down)",
    "menu-on-air": "On Air",
    "menu-off-air": "Off Air",
    "menu-ftb": "FTB",
    "menu-play-pause": "Play / Pause",
    "menu-audio-fade-in": "Main Audio Fade In",
    "menu-audio-fade-out": "Main Audio Fade Out",
    "menu-capture-fullscreen": "Capture Fullscreen",
    "menu-recording-toggle": "Recording",
    "menu-dsk-toggle": "Toggle DSK",
    "menu-mode": "Mode",
    "menu-list-mode-repeat": "List Mode - REPEAT",
    "menu-list-mode-list": "List Mode - LIST",
    "menu-direct-mode": "Direct Mode",
    "menu-soundpad-mode": "Sound-Pad Mode",
    "menu-fillkey-mode": "FILL-KEY Mode",
    "menu-window": "Window",
    "menu-debug-mode": "Debug Mode",
    "menu-fullscreen": "Fullscreen",
    "menu-fullscreen-toggle-minimize-maximize": "Toggle Fullscreen Minimize/Maximize",
    "menu-move-fullscreen": "Move Fullscreen Window",
    "menu-tools": "Tools",
    "menu-tools-atem-connection": "ATEM Connection",
    "menu-help": "Help",
    "menu-about": "About",
    "menu-check-update": "Check Update",
    "menu-readme": "Readme",
    "menu-tools-generate-smpte-bars": "Generate SMPTE color bars",
    "menu-tools-generate-checker": "Generate color checkerboard",
    "menu-tools-generate-1khz-tone": "Generate 1kHz test tone",
    
    "edit-title": "EDIT",
    "playlist-title": "PLAYLIST",
    "on-air-title": "ON AIR",

    "in-point": "IN Point",
    "out-point": "OUT Point",
    "start-mode-title": "START MODE",
    "start-pause-button": "PAUSE",
    "start-play-button": "PLAY",
    "start-fadein-button": "FADE IN",
    "end-mode-title": "END MODE",
    "end-off-button": "OFF",
    "end-pause-button": "PAUSE",
    "end-repeat-button": "REPEAT1",
    "end-next-button": "NEXT",
    "end-ftb-button": "FTB",
    "ftbRate": "Fade-out Duration (sec)",
    "audio-output": "AUDIO OUTPUT",
    "audio-output-level": "AUDIO OUTPUT LEVEL",
    "pfl-button": "PFL",
    "on-air-volume-slider": "Volume Slider",
    "uvc-device": "UVC DEVICE",
    "other-source-title": "OTHER SOURCE",
    "addUVCToPlaylistButton": "ADD LIST",
    "still-capture-title": "STILL CAPTURE TO MP4 / PPTX,PNG TO MP4 DURATION (SEC)",
    "still-button": "CAPTURE",
    "fadeInDuration": "Conversion Duration (sec)",
    "pptxDissolve": "DISSOLVE",
    "dsk-button": "DSK",
    "dsk-title": "DOWN STREAM KEY",
    "list-mode-title": "MODE",
    "list-repeat-button": "REPEAT-ALL",
    "list-list-button": "LIST",
    "directonair-mode-button": "DIRECT",
    "soundpad-mode-button": "SOUND-PAD",
    "fillkey-mode-button": "FILL-KEY",
    "playlist-name-display": "PLAY LIST STORE",
    "playlise-save-button": "SAVE",
    "playlise1-button": "1",
    "playlise2-button": "2",
    "playlise3-button": "3",
    "playlise4-button": "4",
    "playlise5-button": "5",
    "playlisedel-button": "DELETE",
    "playliseclear-button": "CLEAR",
    "file-button": "ADD FILE",
    "cue-button": "ON AIR",
    "on-air-item-fo-button": "F/O",
    "on-air-item-fi-button": "F/I",
    "on-air-fo-button": "F/O",
    "on-air-fi-button": "F/I",
    "playback-speed-control": "PLAYBACK SPEED CONTROL",
    "playback-speed-slider": "Speed Adjustment Slider",
    "playback-speed-input": "Speed Input",
    "fullscreen-shot": "SCREEN SHOT / REC",
    "capture-button": "SCREEN SHOT",
    "rec-button": "REC",
    "off-air-button": "OFF AIR",
    "ftb-off-button": "FTB",
    "on-air-pause-button": "PAUSE",
    "on-air-play-button": "PLAY",
    "playlist-name-title": "ENTER PLAYLIST NAME",
    "playlist-name-save": "SAVE",
    "playlist-name-cancel": "CANCEL",

    // Context menu (playlist item)
    "context-rename-item": "Rename",
    "context-start-mode": "Start Mode",
    "context-end-mode": "End Mode",
    "context-end-mode": "End Mode",
    "context-bg-color": "Background Color",
    "context-bg-color-default": "Default",
    "context-bg-color-red": "Red",
    "context-bg-color-yellow": "Yellow",
    "context-bg-color-blue": "Blue",
    "context-bg-color-green": "Green",
    "context-start-mode-play": "PLAY",
    "context-start-mode-pause": "PAUSE",
    "context-start-mode-fadein": "FADEIN",

    "context-end-mode-next": "NEXT",
    "context-end-mode-off": "OFF",
    "context-end-mode-pause": "PAUSE",
    "context-end-mode-repeat": "REPEAT",
    "context-end-mode-ftb": "FTB",

    "context-copy-item-state": "Copy Item State",
    "context-paste-item-state": "Paste Item State",

    "menu-reset-edit-area": "Reset Edit Area",
    "device-settings-title": "Device Settings",
    "device-loading-message": "Device Loading...",
    "audio-section-title": "Audio",
    "edit-audio-monitor-label": "PFL Audio Monitor Device",
    "onair-audio-output-label": "On-Air Audio Output Device",
    "uvc-audio-mapping-title": "UVC Audio Mapping",
    "restore-on-startup-label": "Restore on next startup",

    "recording-settings-title": "Recording Settings",
    "recording-section-title": "Recording",
    "recording-quality-label": "Recording Quality",
    "recording-quality-high": "High Quality (10Mbps)",
    "recording-quality-standard": "Standard (8Mbps)",
    "recording-quality-performance": "Performance (6Mbps)",
    "recording-filename-prefix-label": "File Name Prefix",
    "recording-save-directory-label": "Save Directory",
    "recording-browse-button": "Browse...",
    "recording-ok-button": "OK",

    "atem-settings-title": "ATEM Connection",
    "atem-control-enable": "Control ATEM from VTR-PON",
    "atem-auto-switch-enable": "Control VTR-PON from ATEM",
    "atem-ip-address-label": "IP Address",
    "atem-input-number-label": "VTR-PON Input Number",
    "atem-switch-delay-label": "Switch Delay (ms)",
    "atem-restore-on-startup-label": "Restore on next startup",
    "atem-save-button": "Save",
    "atem-cancel-button": "Cancel"
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = labels;
} else {
  window.labels = labels;
}