// -----------------------
//     labels.js
//     ver 2.2.9
// -----------------------



const labels = {
  "ja": {

    "menu-file": "ファイル",
    "menu-add-file": "ファイル追加",
    "menu-export-playlist": "プレイリストエクスポート",
    "menu-import-playlist": "プレイリストインポート",
    "menu-device-settings": "デバイス設定",
    "menu-recording-settings": "録画設定",
    "menu-language": "言語",
    "menu-exit": "終了",
    "menu-edit": "編集",
    "menu-toggle-start-mode": "スタートモード切替（Pause/Play/Fadein）",
    "menu-end-mode-off": "エンドモード：OFF",
    "menu-end-mode-pause": "エンドモード：PAUSE",
    "menu-end-mode-ftb": "エンドモード：FTB",
    "menu-end-mode-repeat": "エンドモード：REPEAT",
    "menu-end-mode-next": "エンドモード：NEXT",
    "menu-reset-edit-area": "エディットエリアリセット",
    "menu-set-in-point": "IN点設定",
    "menu-set-out-point": "OUT点設定",
    "menu-copy-item-state": "アイテム状態コピー",
    "menu-paste-item-state": "アイテム状態貼付",
    "menu-playlist": "プレイリスト",
    "menu-playlist1": "プレイリスト1",
    "menu-playlist2": "プレイリスト2",
    "menu-playlist3": "プレイリスト3",
    "menu-playlist4": "プレイリスト4",
    "menu-playlist5": "プレイリスト5",
    "menu-save-mode": "セーブモード",
    "menu-delete-mode": "削除モード",
    "menu-clear-playlist": "クリア",
    "menu-select-item-up": "アイテム選択（上）",
    "menu-select-item-down": "アイテム選択（下）",
    "menu-on-air": "オンエア",
    "menu-off-air": "オフエア",
    "menu-ftb": "FTB",
    "menu-play-pause": "再生／停止",
    "menu-audio-fade-in": "メイン音声フェードイン",
    "menu-audio-fade-out": "メイン音声フェードアウト",
    "menu-capture-fullscreen": "スクリーンショット",
    "menu-recording-toggle": "録画",
    "menu-mode": "モード",
    "menu-list-mode-repeat": "リストモード：REPEAT",
    "menu-list-mode-list": "リストモード：LIST",
    "menu-direct-mode": "ダイレクトモード",
    "menu-soundpad-mode": "サウンドパッドモード",
    "menu-fillkey-mode": "フィルキーモード",
    "menu-window": "ウィンドウ",
    "menu-debug-mode": "デバッグモード",
    "menu-fullscreen": "フルスクリーン",
    "menu-fullscreen-toggle-minimize-maximize": "フルスクリーン画面を最小化/最大化",
    "menu-move-fullscreen": "フルスクリーン移動",
    "menu-help": "ヘルプ",
    "menu-about": "バージョン情報",
    "menu-check-update": "アップデートの確認",
    "menu-readme": "Readme",
    
    "edit-title": "編集",
    "playlist-title": "プレイリスト",
    "on-air-title": "オンエアモニタリング",
    
    "in-point": "イン点",
    "out-point": "アウト点",
    "start-mode-title": "再生開始モード",
    "start-pause-button": "一時停止",
    "start-play-button": "再生",
    "start-fadein-button": "F/I",
    "end-mode-title": "再生終了モード",
    "end-off-button": "オフ",
    "end-pause-button": "ポーズ",
    "end-repeat-button": "繰返し",
    "end-next-button": "次",
    "end-ftb-button": "FTB",
    "ftbRate": "フェードアウト時間（秒）",
    "audio-output-level": "音量設定",
    "audio-output": "音声出力",
    "pfl-button": "PFL",
    "on-air-volume-slider": "音量",
    "uvc-device": "UVCデバイス",
    "other-source-title": "その他ソース",
    "addUVCToPlaylistButton": "リストに追加",
    "still-capture-title": "スチルキャプチャ/PNG動画変換の時間設定",
    "still-button": "キャプチャ",
    "dsk-button": "DSK",
    "fadeInDuration": "変換時間（秒）",
    "list-mode-title": "モード",
    "list-repeat-button": "全リピート",
    "list-list-button": "リストを一巡",
    "directonair-mode-button": "ダイレクト",
    "soundpad-mode-button": "パッド",
    "fillkey-mode-button": "フィルキー",
    "playlist-name-display": "プレイリストストア",
    "playlise-save-button": "保存",
    "playlise1-button": "1",
    "playlise2-button": "2",
    "playlise3-button": "3",
    "playlise4-button": "4",
    "playlise5-button": "5",
    "playlisedel-button": "削除",
    "playliseclear-button": "クリア",
    "file-button": "ファイル追加",
    "cue-button": "オンエア",
    "on-air-item-fo-button": "F/O",
    "on-air-item-fi-button": "F/I",
    "on-air-fo-button": "F/O",
    "on-air-fi-button": "F/I",
    "playback-speed-control": "再生速度",
    "playback-speed-slider": "速度調整",
    "playback-speed-input": "速度",
    "fullscreen-shot": "フルスクリーンキャプチャ / 録画",
    "captuer-button": "キャプチャ",
    "rec-button": "録画",
    "off-air-button": "オフエア",
    "ftb-off-button": "FTB",
    "on-air-pause-button": "一時停止",
    "on-air-play-button": "再生",
    "playlist-name-title": "プレイリスト名を入力してください",
    "playlist-name-save": "保存",
    "playlist-name-cancel": "キャンセル"
  },
  "en": {

    "menu-file": "File",
    "menu-add-file": "Add File",
    "menu-export-playlist": "Export Playlist",
    "menu-import-playlist": "Import Playlist",
    "menu-device-settings": "Device Settings",
    "menu-recording-settings": "Recording Settings",
    "menu-language": "Language",
    "menu-exit": "Exit",
    "menu-edit": "Edit",
    "menu-toggle-start-mode": "Toggle Start Mode (Pause/Play/Fadein)",
    "menu-end-mode-off": "End Mode: OFF",
    "menu-end-mode-pause": "End Mode: PAUSE",
    "menu-end-mode-ftb": "End Mode: FTB",
    "menu-end-mode-repeat": "End Mode: REPEAT",
    "menu-end-mode-next": "End Mode: NEXT",
    "menu-reset-edit-area": "Reset Edit Area",
    "menu-set-in-point": "Set IN Point",
    "menu-set-out-point": "Set OUT Point",
    "menu-copy-item-state": "Copy Item State",
    "menu-paste-item-state": "Paste Item State",
    "menu-playlist": "Playlist",
    "menu-playlist1": "Playlist 1",
    "menu-playlist2": "Playlist 2",
    "menu-playlist3": "Playlist 3",
    "menu-playlist4": "Playlist 4",
    "menu-playlist5": "Playlist 5",
    "menu-save-mode": "Save Mode",
    "menu-delete-mode": "Delete Mode",
    "menu-clear-playlist": "Clear",
    "menu-select-item-up": "Select Item (Up)",
    "menu-select-item-down": "Select Item (Down)",
    "menu-on-air": "On Air",
    "menu-off-air": "Off Air",
    "menu-ftb": "FTB",
    "menu-play-pause": "Play / Pause",
    "menu-audio-fade-in": "Main Audio Fade In",
    "menu-audio-fade-out": "Main Audio Fade Out",
    "menu-capture-fullscreen": "Capture Fullscreen",
    "menu-recording-toggle": "Recording",
    "menu-mode": "Mode",
    "menu-list-mode-repeat": "List Mode - REPEAT",
    "menu-list-mode-list": "List Mode - LIST",
    "menu-direct-mode": "Direct Mode",
    "menu-soundpad-mode": "Sound-Pad Mode",
    "menu-fillkey-mode": "FILL-KEY Mode",
    "menu-window": "Window",
    "menu-debug-mode": "Debug Mode",
    "menu-fullscreen": "Fullscreen",
    "menu-fullscreen-toggle-minimize-maximize": "Toggle Fullscreen Minimize/Maximize",
    "menu-move-fullscreen": "Move Fullscreen Window",
    "menu-help": "Help",
    "menu-about": "About",
    "menu-check-update": "Check Update",
    "menu-readme": "Readme",
    
    "edit-title": "EDIT",
    "playlist-title": "PLAYLIST",
    "on-air-title": "ON AIR",

    "in-point": "IN Point",
    "out-point": "OUT Point",
    "start-mode-title": "START MODE",
    "start-pause-button": "PAUSE",
    "start-play-button": "PLAY",
    "start-fadein-button": "FADE IN",
    "end-mode-title": "END MODE",
    "end-off-button": "OFF",
    "end-pause-button": "PAUSE",
    "end-repeat-button": "REPEAT1",
    "end-next-button": "NEXT",
    "end-ftb-button": "FTB",
    "ftbRate": "Fade-out Duration (sec)",
    "audio-output": "AUDIO OUTPUT",
    "audio-output-level": "AUDIO OUTPUT LEVEL",
    "pfl-button": "PFL",
    "on-air-volume-slider": "Volume Slider",
    "uvc-device": "UVC DEVICE",
    "other-source-title": "OTHER SOURCE",
    "addUVCToPlaylistButton": "ADD LIST",
    "still-capture-title": "STILL CAPTURE TO MP4 / PPTX,PNG TO MP4 DURATION (SEC)",
    "still-button": "CAPTURE",
    "fadeInDuration": "Conversion Duration (sec)",
    "dsk-button": "DSK",
    "list-mode-title": "MODE",
    "list-repeat-button": "REPEAT-ALL",
    "list-list-button": "LIST",
    "directonair-mode-button": "DIRECT",
    "soundpad-mode-button": "SOUND-PAD",
    "fillkey-mode-button": "FILL-KEY",
    "playlist-name-display": "PLAY LIST STORE",
    "playlise-save-button": "SAVE",
    "playlise1-button": "1",
    "playlise2-button": "2",
    "playlise3-button": "3",
    "playlise4-button": "4",
    "playlise5-button": "5",
    "playlisedel-button": "DELETE",
    "playliseclear-button": "CLEAR",
    "file-button": "ADD FILE",
    "cue-button": "ON AIR",
    "on-air-item-fo-button": "F/O",
    "on-air-item-fi-button": "F/I",
    "on-air-fo-button": "F/O",
    "on-air-fi-button": "F/I",
    "playback-speed-control": "PLAYBACK SPEED CONTROL",
    "playback-speed-slider": "Speed Adjustment Slider",
    "playback-speed-input": "Speed Input",
    "fullscreen-shot": "SCREEN SHOT / REC",
    "captuer-button": "SCREEN SHOT",
    "rec-button": "REC",
    "off-air-button": "OFF AIR",
    "ftb-off-button": "FTB",
    "on-air-pause-button": "PAUSE",
    "on-air-play-button": "PLAY",
    "playlist-name-title": "ENTER PLAYLIST NAME",
    "playlist-name-save": "SAVE",
    "playlist-name-cancel": "CANCEL"
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = labels;
} else {
  window.labels = labels;
}
